vich_uploader:
    db_driver: orm

    mappings:
        photo_images:
            uri_prefix:         '%app.path.photo_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.photo_images%'
